### ISSUE TITLE
Content is missing from /courses/21g-049-french-photography-spring-2017/sections/assignments/visual-analysis-papers/

### ISSUE THREAD

**Issue by pdpinch** [mitodl/hugo-course-publisher#151]
### Steps to Reproduce

Compare 
https://ocw-next.netlify.app//courses/21g-049-french-photography-spring-2017/sections/assignments/visual-analysis-papers/
to 
https://ocw.mit.edu/courses/global-languages/21g-049-french-photography-spring-2017/assignments/visual-analysis-papers/

### Expected Behavior

- There should be a body paragraph starting with the text "Over the course of the semester" followed by 8 "week" sections. 
- The next level of sub-nav should be hidden, as I expect will happen once #149 is merged. 

### Actual Behavior

Only the text "null" appears.

**Comment by gumaerc** [comment]
I believe this is a duplicate issue @pdpinch : mitodl/ocw-to-hugo#451

From what we discussed, I believe the structure of this was non-standard and you were going to ask some folks at OCW about it.  I'll take another look at the data though and see what I can find.
