### ISSUE TITLE
home page

### ISSUE THREAD

**Issue by gumaerc** [mitodl/hugo-course-publisher#170]
As a user, I'd like to be greeted with a relevant home page at the root of the site.

#### Designs and Mockups

https://projects.invisionapp.com/d/main?origin=v7#/projects/prototypes/18609637

#### Acceptance Criteria:

- [x] Header
- [x] Title & search box
- [x] Dismissible beta dialog
- [ ] New courses section
- [x] Give now section with give button
- [x] Social media section
- [x] Newsletter subscribe section

#### Out of Scope

- OCW News will only be lorem ipsum for now

**Comment by pdpinch** [comment]
Let's skip the "OCW News" section for now. We can add that in when it becomes clearer. 

The Give Now, social media and subscribe stuff can all be stubbed with a "coming soon" message.
