### ISSUE TITLE
Missing content after video gallery

### ISSUE THREAD

**Issue by pdpinch** [mitodl/hugo-course-publisher#182]
### Steps to Reproduce

Compare https://master--ocw-next.netlify.app/courses/ec-711-d-lab-energy-spring-2011/sections/intro-energy-basics-human-power/ and https://ocw.mit.edu/courses/edgerton-center/ec-711-d-lab-energy-spring-2011/intro-energy-basics-human-power/

### Expected Behavior

- display Readings and assignments, below the video gallery

### Actual Behavior

- Readings and Assignments are missing
- "null" text appears above video gallery

### out of scope

- we don't need "Subscribe to this collection" RSS link

**Comment by aliceriot** [comment]
looks like the issue is over on the ocw-to-hugo side, since the markdown file for this page has `"null"` as it's content.
