### ISSUE TITLE
full text search of Resources

### ISSUE THREAD

**Issue by pdpinch** [mitodl/hugo-course-publisher#208]
As a user, I'd like to be able to search for text in OCW resources 

Part of #207

#### Designs and Mockups

https://projects.invisionapp.com/d/main?origin=v7#/console/18609637/431546014/preview?scrollOffset=0

#### Acceptance Criteria:

- [ ] full text search of resources, similar to course search 
- [ ] No facets
- [ ] return basic cards in an infinite scroll 
- [ ] link from cards to resources would be nice, but could be a follow-up PR

#### Out of Scope

- thumbnails
- Link from search results to resource page 
- Facets

**Comment by mbertrand** [comment]
@pdpinch should resources other than PDF's, HTML pages, and videos be excluded from results for now?  Images, word docs, spreadsheets, code files, csv's, etc.

**Comment by pdpinch** [comment]
Yes. For now we want to focus on the resource file types that we think will be the most useful: PDFs, videos and HTML.

**Comment by abdulkdawson** [comment]
@mbertrand here is the "Files" icon for search 
![Files](https://user-images.githubusercontent.com/49685474/112670269-131dd600-8e37-11eb-94f3-d2883ac43ba2.png)

**Comment by abdulkdawson** [comment]
@mbertrand Here is a version titled File minus the "s"
![File_Icon](https://user-images.githubusercontent.com/49685474/112670420-43fe0b00-8e37-11eb-8db3-c256fd59f535.png)
