### ISSUE TITLE
Course search should return courses containing resources that match the search term

### ISSUE THREAD

**Issue by pdpinch** [mitodl/hugo-course-publisher#209]
As a user searching for courses, I expect the search results to include courses where the search term is mentioned _anywhere_ in the course, not just in the course description.

We implemented this already in Open, and ported it to OCW, but it was removed inadvertently in PR #172. It should be easy as reverting the relevant the following lines in https://github.com/mitodl/hugo-course-publisher/commit/ca9c3e6690c4d758c1e7e26cf7c3e908efe337e4#diff-056cfd3919133e6120edb4d9c64a6501L119-L143

#### Acceptance Criteria:

- [ ] a search on the word "albedo" should return the same number of courses on [ocw]( https://ocw-beta.odl.mit.edu/search/?q=albedo) as it does in [Open Learn](https://discussions-rc.odl.mit.edu/learn/search?o=OCW&q=albedo&type=course).

**Comment by pdpinch** [comment]
I believe @aliceriot closed this with #210

**Comment by aliceriot** [comment]
yep this should be all set now
