### ISSUE TITLE
env variables aren't pulled in properly in some cases

### ISSUE THREAD

**Issue by gumaerc** [mitodl/hugo-course-publisher#211]
### Steps to Reproduce

Set any of the `ocw-to-hugo` env variables for the `import:ocw*` commands in a `.env` file and try and run any of the import commands

### Expected Behavior

The correct values are pulled from the environment and the import runs successfully

### Actual Behavior

There are errors like:

```
UnhandledPromiseRejectionWarning: Error: To download courses from AWS, you must specify the -c argument.  For more information, see README.md
```

**Comment by noisecapella** [comment]
Maybe this is related? https://github.com/mitodl/ocw-to-hugo/pull/78

**Comment by gumaerc** [comment]
That env var you pointed out was definitely misspelled, but I don't think that is causing this particular issue.  If the region in the config object is undefined I believe it just uses the default region.  I believe the issue here that when you call env variables directly in package.json with the bash syntax i.e. `$OCW_TO_HUGO_INPUT` then this value is pulled directly from the system environment.  We are using the node package `dotenv-webpack` to pull in values set in a `.env` file so values set in that file don't work when called in this way.  Also, @aliceriot pointed out that package.json commands are called using `sh` and if you use a different shell like `zsh` then your environment isn't pulled in.  I recommend that instead of the package.json commands calling `ocw-to-hugo` directly, the should call a build script that initializes `dotenv` properly so environment variables from any source they're supposed to come from, be it a `.env` file, your local environment or an AWS instance profile work as expected.
