### ISSUE TITLE
Course search: Topics facet

### ISSUE THREAD

**Issue by pdpinch** [mitodl/hugo-course-publisher#215]
As a search user, I want to filter search results by topic.

#### Designs and Mockups

As of 9/21 
https://projects.invisionapp.com/d/main?origin=v7#/console/18609637/430321024/preview?scrollOffset=0

#### Acceptance Criteria:

- [x] Label the facet "Topics"
- [ ] values correspond to the 2nd level of course topics, aka subtopic or subfeature 
- [ ] facets should be sorted by frequency, with the highest hit count at the top (same as Open) 
- [ ] display 10 facets, with a scroll bar to view the whole list 
- [ ] include a search box for topics, since there are so many (same as Open)

**Comment by aliceriot** [comment]
@pdpinch is 'subtopic or subfeature' what we currently do in Open?

I will copy over the existing component from Open, and we can make any visual tweaks we want to it over here.
