### ISSUE TITLE
Couse search: Level facet

### ISSUE THREAD

**Issue by pdpinch** [mitodl/hugo-course-publisher#216]
As a search user, I'd like to filter the search results by the level of the course, i.e. undergraduate or graduate.

Courses can have multiple values for "level". 

Non credit courses don't have a level per se, so they are tagged "Non Credit" 

#### Designs and Mockups

https://projects.invisionapp.com/d/main?origin=v7#/console/18609637/430321024/preview?scrollOffset=0

#### Acceptance Criteria:

- [ ] Label the facet "Levels"
- [ ] We expect the data to have 3 values: "Undergraduate" "Graduate" and "Non Credit" 
- [ ] basic checkboxes

**Comment by aliceriot** [comment]
it looks like this one isn't added to the elasticsearc index yet - @abeglova would you possibly be able to confirm whether that's true or not?
