### ISSUE TITLE
Course search: Department facet

### ISSUE THREAD

**Issue by pdpinch** [mitodl/hugo-course-publisher#217]
As a search user, I'd like to be able to filter search results by department. 

As a MIT department member, I'd like to be able to easy filter down to the courses in my department. 

#### Designs and Mockups

https://projects.invisionapp.com/d/main?origin=v7#/console/18609637/430321024/preview?scrollOffset=0

#### Acceptance Criteria:

- [ ] Similar UI to Topics, with 10 values visble at a time and scrollbar
- [ ] search box similar to the Topics facet

**Comment by aliceriot** [comment]
ok! just got a basic version of this in place:

![Screenshot from 2020-10-02 11-21-46](https://user-images.githubusercontent.com/6207644/94940451-886ca780-04a1-11eb-9ee9-44b68046f469.png)

I'll need to make one small change in Open and one in course-search-utils to get this to work.

**Comment by aliceriot** [comment]
just merged the PR in Open (mitodl/open-discussions#3173)
