### ISSUE TITLE
Table styling in 1.00 sp12 readings section

### ISSUE THREAD

**Issue by pdpinch** [mitodl/hugo-course-publisher#219]
### Steps to Reproduce

Compare the [legacy page](https://ocw.mit.edu/courses/civil-and-environmental-engineering/1-00-introduction-to-computers-and-engineering-problem-solving-spring-2012/readings/)  to the [next gen page](https://ocw-beta.odl.mit.edu/courses/1-00-introduction-to-computers-and-engineering-problem-solving-spring-2012/sections/readings/)

<img src=https://user-images.githubusercontent.com/430126/93801190-a61f4e80-fc0f-11ea-9683-948517f29ed7.png border=1 width="45%"><img src=https://user-images.githubusercontent.com/430126/93801279-bf27ff80-fc0f-11ea-9e52-633af10c3efe.png border=1 width="45%">

### Expected Behavior

The table should be styled in a way that makes it intelligible. 

### Actual Behavior

It appears that the one large table has been broken up into multiple simpler tables. This isn't necessarily a bad thing, but the association of the column headers with the rest of the table has been lost.

**Comment by gumaerc** [comment]
The legacy tables use a `colspan` attribute to extend to the end of the table like that.  The Github flavored markdown that makes the tables work doesn't support using `colspan`, so I had to break up the tables as you see there.  Knowing what I know now about shortcodes though, I could probably take another crack at tables using shortcodes if we want to cover cases like this.

**Comment by gumaerc** [comment]
Another option would be to use CSS to make sure that column widths are the same between the tables so they line up.
