### ISSUE TITLE
Drawer: Show more lines of course metadata by default

### ISSUE THREAD

**Issue by pdpinch** [mitodl/hugo-course-publisher#220]
As a user, I'd like to see more of the instructor list before I have to click the reveal (▼) button to show the whole list.

For example, when there are 10 instructors, the first 3 lines of them display with the 4th faded. Clicking the reveal button shows all the lines. 

#### Designs and Mockups

hopefully not necessary?

#### Acceptance Criteria:

- [ ] default to showing 3 lines with the 4th faded out, instead of the current 1 line with the 2nd faded out.

**Comment by pdpinch** [comment]
Quick update: each field in the drawer should display 3 lines by default, not just the instructor section. I'll update the description to reflect this when I can.

**Comment by gumaerc** [comment]
@pdpinch Could you clarify if we want to do this for all the partially revealed lists, or just the instructor list?

**Comment by pdpinch** [comment]
All lists. See https://projects.invisionapp.com/d/main#/console/18609637/407710624/preview
