### ISSUE TITLE
mobile design for search

### ISSUE THREAD

**Issue by aliceriot** [mitodl/hugo-course-publisher#224]
need to implement the mobile designs for the search, specifically to deal with the filter display.

designs here: https://projects.invisionapp.com/d/main#/projects/prototypes/18552410

**Comment by mbertrand** [comment]
@abdulkdawson @pdpinch should the filter display behave and look about the same as open-discussions in the mobile view when expanded?

<img width="412" alt="Screen Shot 2020-10-06 at 12 51 28 PM" src="https://user-images.githubusercontent.com/187676/95232592-b9ffae80-07d2-11eb-9426-2ccfac7c315b.png">
