### ISSUE TITLE
Search style fixes

### ISSUE THREAD

**Issue by pdpinch** [mitodl/hugo-course-publisher#226]
After we implemented the topic facet, we noticed a couple of small issues. 

- [x] The width of the facet and the space between the facet and the search results don't match the design
- [x] In Firefox, the height of the search boxes is too tall -- possibly because the hint text is misaligned?
- [x] When hovering over a facet with a long label, the text can wrap which breaks the layout. In Open, we truncated long labels with a ellipsis (...) 
- [x] The loading animation is shorter than the page, which leads to the page scrolling whenever the user adds or removes a facet. The easy fix would be to copy the same loading animation from Open

We should try to fix all these issues before our next release to the ocw-beta site.

**Comment by aliceriot** [comment]
for the firefox placeholder text - it looks as though this is a bootstrap thing. there's a `:placeholder` pseudo-element and bootstrap puts `line-height: 1` on it which makes it do strange things - it's not clear to me why this isn't an issue in chrome though.
