### ISSUE TITLE
Search: Link course cards to course CHPs

### ISSUE THREAD

**Issue by pdpinch** [mitodl/hugo-course-publisher#227]
As a user, I'd like to link from the search results to the courses that I find. 

#### Acceptance Criteria:

- [ ] Make sure that the necessary data for creating a link is in the Open search index
- [ ] if possible, log an error to sentry if the user clicks on a course link that doesn't exist

**Comment by mbertrand** [comment]
@pdpinch do you want to log a sentry error for every 404, or just ones that seem to match a course home page pattern?

**Comment by mbertrand** [comment]
actually I'm not sure if it's possible at the moment, on ocw-beta I get an ugly 404 from AWS S3, the app doesn't seem to handle 404s itself (yet).
https://ocw-beta.odl.mit.edu/courses/1-017-computing-and-data-analysis-for-environmental-oops-fall-2003/

**Comment by pdpinch** [comment]
If it's difficult at all, let's skip for now and revisit later. 

I should have written down what the goal was... My concern is that there's a decent chance the search index won't match the courses published by Hugo. I'd like to have some way to log and alert on these, so someone can investigate. "log an error to sentry" is just a suggestion.
