### ISSUE TITLE
Search: update course cards

### ISSUE THREAD

**Issue by pdpinch** [mitodl/hugo-course-publisher#230]
#### Designs and Mockups

See https://projects.invisionapp.com/share/TYYM755E9FJ#/screens/430328458_OCW_Course_Search_Learning_Landing_Page_Courses09-01-2020_No_Facets

#### Acceptance Criteria:

- [ ] remove "Course" 
- [ ] add course number
- [ ] add Level 
- [ ] s/Subject/Topic/
- [ ] add instructors
- [ ] update styling 
- [ ] anything else you see in the design

**Comment by mbertrand** [comment]
@pdpinch @abdulkdawson in the designs it looks like some result cards are taller than others if there are multiple lines of topics or instructors.  Is that intended?  I think in open they are always the same height and topics are truncated if necessary to keep them to 1 line.

**Comment by abdulkdawson** [comment]
@mbertrand This was done purposely. The cards can be varying heights based on the amount of meta data.
