### ISSUE TITLE
Home: Carousel and Mobile version of new courses section 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/hugo-course-publisher#268]
Follow on to #240 

#### Designs and Mockups

https://invis.io/P4U3K9MRCA2#/435361266_OCW_Mobile_HomePage_10_21_2020

#### Acceptance Criteria:

- [ ] At desktop width, show (up to) 4 cards and allow the user to cycle through the whole set (default 10). 
- [ ] At mobile with, show one card and allow the user to cycle through the whole set (default 10). 

#### Out of Scope

- No "View All" link

**Comment by abdulkdawson** [comment]
@noisecapella Here is the mock for the mobile version of the homepage:[https://projects.invisionapp.com/d/main#/console/18552410/435361266/comments/137375721](https://projects.invisionapp.com/d/main#/console/18552410/435361266/comments/137375721)
