### ISSUE TITLE
Home: reduce previous/next font size on desktop

### ISSUE THREAD

**Issue by noisecapella** [mitodl/hugo-course-publisher#292]
The previous and next buttons currently look like this on desktop:
![Screenshot from 2020-11-03 14-24-46](https://user-images.githubusercontent.com/863262/98031385-65a31b00-1de0-11eb-9978-c7f627194041.png)

But the mockup looks like this:
![Screenshot from 2020-11-03 14-25-02](https://user-images.githubusercontent.com/863262/98031408-6fc51980-1de0-11eb-9387-d23f3f4fb4ac.png)

We should shrink the font size of the next/previous buttons and change the color of "Featured Courses" while we're here. Any other thoughts @abdulkdawson?

**Comment by abdulkdawson** [comment]
@noisecapella The buttons should be smaller yes, but the mock shows them as transparent which is a mistake. The buttons are still white. The section title (Featured Courses) should be changed to reflect the current mock.

**Comment by aliceriot** [comment]
this is what it currently looks like:

![Screenshot from 2020-12-02 10-19-03](https://user-images.githubusercontent.com/6207644/100892057-edd01b00-3487-11eb-8fde-9cb6ac1f845e.png)

I adjusted this in #363 for #355
