### ISSUE TITLE
Course Info: Link from instructor names to search 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/hugo-course-publisher#306]
As a user, I'd like to click on an instructor's name in the course info drawer and open a search for all their courses. 

#### Acceptance Criteria:

- [x] index instructor name as a searchable field
- [x] link from instructors' name on the CHP (course home page) to search
- [x] link from instructors' names on course (interior) pages to search

**Comment by mbertrand** [comment]
"Instructors" is already indexed as a searchable _**text**_ field in Elasticsearch, whereas all the other facet fields are indexed as _**keyword**_ fields.  Consequently, this error occurs when trying to aggregate:


> "Fielddata is disabled on text fields by default. Set fielddata=true on [runs.instructors] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.""


I could do as suggested and set fielddata=true, but I'm a little concerned about the memory warning.  If I convert it to a keyword field, then searching solely by instructor last name won't work anymore, a user would have to search by the instructor's full name, matching exactly.  For example. the course "Control of Manufacturing Processes (SMA 6303)" has an instructor named "Duane Boning".  On discussions-rc, searching for 'boning' will return that class as the top result.  If I convert the field to a keyword, it is no longer returned unless I search for '"Duane Boning"' in quotes.

One other possibility is indexing the field twice, as a text field and as a keyword field.
