### ISSUE TITLE
Course pages: style to match new design 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/hugo-course-publisher#311]
#### Designs and Mockups

https://invis.io/XGZCARPAHNW#/435659054_OCW_Course_Syllabus_Page_Color_10-23-2020_
https://invis.io/WXZ7DFDMDY5#/435659055_OCW_Course_Home_Page_Color_10-22-2020_v2_Copy

#### Acceptance Criteria:

- [x] Button to hide course info drawer, even at widest desktop view
- [x] expand central content div when drawer is closed 
- [x] Link course info where appropriate (#306 #307 #309)
- [x] #310 Remove download button(s)
- [x] screenshot of mobile version 
- [x] screenshot of syllabus page, video gallery page, image gallery page 
- [x] Same course banner as CHP (Course home page)
  - [x] flat color for now, no outline
  - [x] course avatar/icon will be optional; omit for now

#### Related issues

- consistent site header

**Comment by gumaerc** [comment]
![image](https://user-images.githubusercontent.com/12089658/99699956-9c279980-2a60-11eb-988f-7f7e6454892b.png)
![image](https://user-images.githubusercontent.com/12089658/99700034-b19cc380-2a60-11eb-8725-9adaa6a78804.png)
![image](https://user-images.githubusercontent.com/12089658/99700200-de50db00-2a60-11eb-8ecc-e37cc1c845cf.png)
![image](https://user-images.githubusercontent.com/12089658/99700273-f3c60500-2a60-11eb-90ff-e16627643a86.png)

**Comment by gumaerc** [comment]
Closing this as these changes have all been merged
