### ISSUE TITLE
CHP: style to match new design 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/hugo-course-publisher#312]
Course Home page new design 

#### Designs and Mockups

https://invis.io/ZAZ6VJ2HRSP#/435537972_OCW_Course_Home_Page_Color_10-22-2020_v2
https://invis.io/QFZ8KA9SH2P#/435953154_OCW_Course_Home_Page_Color_10-27-2020_Course_Info_Collapsed_V2

#### Acceptance Criteria:

- [x]  Same course banner as interior course pages
  - [x] flat color for now, no outline
  - [x] course avatar/icon will be optional; omit for now
- [x] no course drawer on CHP
- [x] large, variably height course image
- [ ] 3 lines of course description display on load, click to read more
- [x] 3 lines of course info display on load, click to read more 
- [x] course feature icons
- [x] screenshot of mobile version 
- [x] screenshot of course with short image, and screenshot of a course with a tall image 

#### Out of Scope

- "Other Versions" (below course features)

**Comment by noisecapella** [comment]
Is this a good reference for the mobile page? https://projects.invisionapp.com/share/P4U3K9MRCA2#/screens/390108052

**Comment by abdulkdawson** [comment]
@noisecapella Yes I have to update the add the colors to reflect what has been done on desktop but the structure is correct here.

**Comment by abdulkdawson** [comment]
@noisecapella Hold off for a sec I realized there are is a few changes I have to make. I'll message you in about 15min when I complete the changes and the mock should be good to go.

**Comment by abdulkdawson** [comment]
@noisecapella Here is the updated mock. Thanks for the patience. [https://projects.invisionapp.com/d/main?origin=v7#/console/18552410/390108052/preview?scrollOffset=1932](https://projects.invisionapp.com/d/main?origin=v7#/console/18552410/390108052/preview?scrollOffset=1932)

**Comment by noisecapella** [comment]
@abdulkdawson Thanks. Should the content inside the course info drawer remain as is?
![Screenshot from 2020-11-10 11-17-20](https://user-images.githubusercontent.com/863262/98700625-61c64a00-2346-11eb-87fd-6c79ad19445a.png)

**Comment by noisecapella** [comment]
Also @abdulkdawson should the max width of all pages be 1664px or just the course home page?

**Comment by abdulkdawson** [comment]
@noisecapella The max width could be 1664px for all pages. The mobile course info has been updated as well. I'll provide the link for that.

**Comment by abdulkdawson** [comment]
@noisecapella Here is the updated course info drawer. [https://projects.invisionapp.com/d/main?origin=v7#/console/18552410/402028575/preview?scrollOffset=3520.5](https://projects.invisionapp.com/d/main?origin=v7#/console/18552410/402028575/preview?scrollOffset=3520.5)

**Comment by noisecapella** [comment]
What does the "Read more" link do on the course description? Is that a separate page or expanding to a second paragraph?

**Comment by noisecapella** [comment]
@abdulkdawson here's the link example. This is after the content has already been expanded: ![Screenshot from 2020-11-12 09-22-28](https://user-images.githubusercontent.com/863262/98951812-b2fe4700-24c8-11eb-966f-b36666650bd5.png)

**Comment by noisecapella** [comment]
@abdulkdawson What should the topics look like if there are more than one topic? This is what it looks like currently:
![Screenshot from 2020-11-12 11-46-25](https://user-images.githubusercontent.com/863262/98969334-ba2f5000-24dc-11eb-94cf-70708e96253b.png)

That roughly matches the mobile screenshot:
![Screenshot from 2020-11-12 11-47-10](https://user-images.githubusercontent.com/863262/98969416-d16e3d80-24dc-11eb-8cd4-bff8f791a637.png)


But the desktop screenshot looks different and I'm not sure what should be shown here:
![Screenshot from 2020-11-12 11-47-40](https://user-images.githubusercontent.com/863262/98969484-e1861d00-24dc-11eb-8618-7f56ce378af7.png)

**Comment by abdulkdawson** [comment]
@noisecapella The desktop version should be the same as the mobile version. But that only goes for the sliding course infor sections. On the Course home page which you have at the bottom should look as it is in the mock. If there is more than one topic is just creates another line below the first topic.
<img width="992" alt="Screen Shot 2020-11-12 at 2 18 36 PM" src="https://user-images.githubusercontent.com/49685474/98985717-f620e000-24f1-11eb-89d4-6db5cf0d0337.png">

**Comment by abdulkdawson** [comment]
@noisecapella Something like this
<img width="329" alt="Screen Shot 2020-11-12 at 2 22 46 PM" src="https://user-images.githubusercontent.com/49685474/98986170-8bbc6f80-24f2-11eb-8fd5-ddf07262afb3.png">

**Comment by noisecapella** [comment]
@pdpinch where should I get the course feature icons from?

**Comment by noisecapella** [comment]
@abdulkdawson Do you know what the colors should be here approximately? https://projects.invisionapp.com/d/main?origin=v7#/console/18552410/403040977/preview?scrollOffset=1932#project_console

**Comment by pdpinch** [comment]
@noisecapella can you check off what's merged on this now? 

What's left?
