### ISSUE TITLE
Home: update styling and implement top features

### ISSUE THREAD

**Issue by pdpinch** [mitodl/hugo-course-publisher#314]
Implement the more stable parts of the new home page

#### Designs and Mockups

https://invis.io/DFZBR47WPA7#/436781958_OCW_NexGen_Homepage_11-04-2020_V2

#### Acceptance Criteria:

- [x] Search box (but not the 3 red buttons below)
- [x] Tag line box
  - [x] "Unlocking Knowledge..." 
  - [x] "Learn More" displays "coming soon" pop-up
- [x] New courses (should already be done)
- [x] restyle social buttons
- [x] add corporate logos 
- [x] implement mobile view (https://projects.invisionapp.com/d/main?origin=v7#/console/18552410/437726301/preview?scrollOffset=1705.5)

#### Out of Scope

- Discover Topics
- OCW News
- Learner Stories

**Comment by aliceriot** [comment]
@pdpinch @abdulkdawson quick question on the restyling of the search box. Currently we use the same component on the home page and on the search page, and right now they're styled pretty much the same way on those two pages:

![Screenshot from 2020-11-09 09-53-34](https://user-images.githubusercontent.com/6207644/98556877-88668100-2271-11eb-950e-a798e9af4be8.png)
![Screenshot from 2020-11-09 09-53-27](https://user-images.githubusercontent.com/6207644/98556879-88ff1780-2271-11eb-8ab1-b92d71750976.png)

my question is, as we're restyling the home page how should the search page change? I took a quick look on invision but didn't see updated designs for the search page that show a new search box design there.

**Comment by pdpinch** [comment]
Repeating what I said in Slack a few days ago: the styling of the search box on the search results page (/search) is going to change, but the design isn't settled yet. You can leave it as is for now.

**Comment by aliceriot** [comment]
@abdulkdawson is there a mobile design for this one yet?

**Comment by aliceriot** [comment]
I took a stab at a basic mobile-ish thing for now, basically when the screen gets more narrow it switches from a row to a column layout for the search box and the blue text box.

**Comment by abdulkdawson** [comment]
@aliceriot i'm working on the mobile side as we finalize the desktop version.

**Comment by aliceriot** [comment]
@abdulkdawson @pdpinch it says here 'restyle social buttons' but looking at the current implementation and the designs they look like they're already mostly good:

implementation:
![Screenshot from 2020-11-18 09-48-30](https://user-images.githubusercontent.com/6207644/99545483-6bbdfd80-2983-11eb-8318-0eeb51ef11da.png)


design:

![Screenshot from 2020-11-18 09-48-40](https://user-images.githubusercontent.com/6207644/99545466-682a7680-2983-11eb-800f-73c5c5491f03.png)

I'll make a few adjustments to get the font sizes closer.

One question though for @abdulkdawson, on a larger display should that blue band extend to the edge of the screen?

also, do you have an asset for the geometric shapes background used behind the course cards in the design? Just realized I also need the assets for the corporate logos

**Comment by aliceriot** [comment]
re: my question about the blue bar, this is what it currently looks like on a wider monitor:

![Screenshot from 2020-11-18 10-00-04](https://user-images.githubusercontent.com/6207644/99546955-fb17e080-2984-11eb-8546-e33c6230f8fc.png)

**Comment by abdulkdawson** [comment]
@aliceriot Yes, the blue background should stretch the width of the page.
