### ISSUE TITLE
Use Hugo Data Templates instead of Front Matter for Course Info

### ISSUE THREAD

**Issue by gumaerc** [mitodl/hugo-course-publisher#326]
As a developer, I'd like to store course metadata in [Hugo Data Templates](https://gohugo.io/templates/data-templates/) instead of [Front Matter](https://gohugo.io/content-management/front-matter/) on the course home page to store the `course_info` object and potentially other data.  Currently to access this data on pages that aren't the course home page you need to make a partial and pass that partial into `chp_partial.html`.  It's not a terrible solution, but this could be done in a much more straightforward manner by just using JSON based Data Templates.

Basically, instead of putting the bulk of course metadata directly into the course markdown files at `site/content/courses`, that information would be stored in JSON files inside `site/data/courses`.  For example, `site/data/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016.json` would be accessed within a page template like so:

```
{{ $course  := $.Site.Data.courses.Get .Params.course_id }}
{{ $courseInfo := $course.course_info }}
```

The major benefit to this would be negating the need to use `chp_partial.html` to gain the context of the course home page.  The above code would work on any page within the site as we are already putting `course_id` into every markdown file.  A potential downside (depending on how you look at it) would be the data not being centralized and being spread across 2 folders.  One of the factors that made me originally decide to put this information into the Front Matter of the course home page was for compatibility with Netlify CMS and potentially other existing static site CMS's.  However, that's looking like less of a concern as we have decided to provide our own content management.

**Comment by aliceriot** [comment]
that does seem like it would be a somewhat cleaner way to access this stuff and would make our markdown files a little bit cleaner. I guess to do so we'd need to refactor `ocw-to-hugo` and then have a PR where we upgraded `ocw-to-hugo` and did some refactors in `hugo-course-publisher` in order to work with that new output.

Would any changes to our deploy pipeline be necessary?

**Comment by noisecapella** [comment]
Is the JSON in `site/data` meant to be the parsed JSON file or some other format?

**Comment by gumaerc** [comment]
@aliceriot  I don't believe any changes would be necessary in the build process from a devops perspective.  Although, since `ocw-to-hugo` would be outputting to more than just the `site/content` folder we'll need to change the various package scripts in `hugo-course-publisher` that use it to output to simply `site`.  This way, `ocw-to-hugo` can write to the `data` folder as well.  In the end Hugo will output the same HTML it always does.

@noisecapella I think we should move data here that doesn't need to be in the Front Matter for build purposes.  For instance, keys such as `type` and `layout` tell Hugo how to categorize the page a given markdown file represents.  I think the `course_info` object might not even be necessary.  I'm fairly certain I put all of that info onto one object for ease of passing it into the partial.  Realistically, I think all of the keys inside it, as well as the non-Hugo related keys currently in Front Matter could be moved over.

**Comment by pdpinch** [comment]
Is there an easy way to see before and after?
