### ISSUE TITLE
Fix title tag for syllabus and other course pages

### ISSUE THREAD

**Issue by noisecapella** [mitodl/hugo-course-publisher#328]
This would be part of #327 but some course information is missing on the syllabus page so the title is incomplete. It will show up as `Syllabus | MIT OpenCourseWare | Free Online Course Materials`, but it should show up as `Syllabus | Single Variable Calculus | Mathematics | MIT OpenCourseWare` for example.

We could update ocw-to-hugo to write out `course_info` for the syllabus and other markdown files. However we may want to wait for #326 instead which would also fix the issue.

**Comment by pdpinch** [comment]
I believe this has been fixed. On https://ocwnext.odl.mit.edu/courses/21a-461-what-is-capitalism-fall-2013/sections/syllabus/ i see 

```
<title>Syllabus | What is Capitalism? | Anthropology | OCW Course Hugo Starter</title>
```

which looks correct to me.
