### ISSUE TITLE
put `Cache-Control` header on JS and CSS assets

### ISSUE THREAD

**Issue by aliceriot** [mitodl/hugo-course-publisher#330]
Currently we don't set this header on our JS and CSS assets, which means that users' browsers aren't going to cache these assets as aggressively as we'd like. We currently use webpack's content-hashing support to ensure that each webpack build produces assets with unique filenames (`main.8087f.css` and so on) so we can safely cache these assets without worrying about the user accessing the site with an outdated JS bundle in the future.

Currently these are the headers set on these assets:

![Screenshot from 2020-11-10 11-40-12](https://user-images.githubusercontent.com/6207644/98703576-a3a4bf80-2349-11eb-8a2e-c2e2e166883c.png)

the `etag` header is content-based, and allows the browser to check whether it has the latest version of the file without requesting the whole file, but this check is currently being made for these resources on every single page load. You can see that in the network tab:

![Screenshot from 2020-11-10 11-41-54](https://user-images.githubusercontent.com/6207644/98703749-d9e23f00-2349-11eb-9134-abbfb39cc910.png)

for our `main.8087f.css` and `main.8087f.js` the server returns a 304 (not modified) without the browser having to download the whole file, so some bandwidth is saved there, but these two extra requests add overhead on each page-load which is totally unnecessary. If we added `Cache-Control: max-age=315360000` on the response for these assets the browser would just go straight to the disk cache without firing off the request and waiting for the 304 before doing so.

**Comment by aliceriot** [comment]
@blarghmatey @markbreedlove where would we need to make a configuration change to set this up?

**Comment by markbreedlove** [comment]
This is a Fastly configuration issue. I'll look into it ...

**Comment by markbreedlove** [comment]
@aliceriot Are there any other buildpack assets other than `main.<hash>.<css|js>` ?

I am evaluating how cautious to be about applying the cache duration, in case there are some CSS and JS assets that do not have the unique identifiers. Wondering how to identify the ones that need it. If there are none besides these "main" ones, then it's easy. Or if all the assets fit the same filename pattern, it's easy. Otherwise, I'm wondering about putting the assets into their own folder.

**Comment by aliceriot** [comment]
I think to start out we could do it just for `main.[hash].[css|js]` - there are a few other things that we include from npm like Mathjax which don't get built with a hash, so we don't want to put the header on those, I think

**Comment by markbreedlove** [comment]
@aliceriot  I've configured Fastly (both QA and production) to set that Cache-Control header for files matching the regex `^/main\.[0-9a-f]+\.(css|js)`

**Comment by aliceriot** [comment]
Nice! Just checked on prod and it's pulling those right from the disk cache without the browser making any request to the server:

![Screenshot from 2020-11-23 11-30-31](https://user-images.githubusercontent.com/6207644/99988253-6c89d180-2d7f-11eb-9938-99da222c0fab.png)

We may want to further optimize this in the future, but I think we can close this for now.
