### ISSUE TITLE
Embedded podcast player is getting stripped 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/hugo-course-publisher#335]
### Expected Behavior

legacy: https://ocw.mit.edu/courses/sloan-school-of-management/15-667-negotiation-and-conflict-management-spring-2001/instructor-insights/

### Actual Behavior

next: https://ocwnext.odl.mit.edu/courses/15-667-negotiation-and-conflict-management-spring-2001/sections/instructor-insights/

**Comment by aliceriot** [comment]
just took a quick look at this, it looks like we first need to make a change on the `ocw-to-hugo` side. In the HTML for this page there's an iframe which renders the player:

```
<iframe scrolling="no" seamless="" src="https://player.simplecast.com/e31edbb0-e4ac-4d9f-aebc-3d613c2f972c?dark=false" width="100%" height="200px" frameborder="no"></iframe>
```

the markdown for the page, produced by `ocw-to-hugo`, looks like this:

```md
---
title: Instructor Insights
course_id: 15-667-negotiation-and-conflict-management-spring-2001
type: course
layout: course_section
menu:
  15-667-negotiation-and-conflict-management-spring-2001:
    identifier: 7d550841de105fb23254c53bd33fde6f
    name: Instructor Insights
    weight: 30
---

{{< anchor "insights" >}}{{< /anchor >}}

Instructor Insights
-------------------

Below, Worcester State University Professor Elizabeth Siler shares with MIT Professor Mary Rowe how she's remixed Prof. Rowe’s open educational resources in 15.667 to teach undergraduates the art of negotiation.

Discussing real life is how you learn negotiation.

— Prof. Mary Rowe

Many instructors in recent years have turned to open educational resources (OER) so that their students don’t have to pay for an expensive textbook. And that is indeed one of the foremost benefits of OER. But Professor Elizabeth Siler, who teaches at Worcester State University, has found that using OER offers advantages to instructors too: doing so allows you to teach the material you think your students need to learn, and to teach that material the way you think your students need to learn it, rather than being tied to a prepackaged sequence of material. Professor Siler enjoys being able to select and adapt material for her courses from publicly-available sources. One source that she’s used successfully in teaching negotiation at WSU is the OpenCourseWare version of a course originally taught at MIT by Professor Mary Rowe. In this episode, we talk with both Professor Siler and Professor Rowe about why instructors might decide to share, reuse, and remix course materials, and how that decision plays out in teaching actual courses like their own courses in negotiation.
```

the iframe has been stripped out. So we'll have to figure out a way to recognize these in `ocw-to-hugo`, include them, possibly using a hugo shortcode, and then render them here.

My guess is we should be able to do something like hugo's built-in `{{< youtube $VIDEO_ID >}}` or `{{< tweet $TWEET_ID >}}` shortcodes, we'd just have one like `{{< simplecast $FILE_ID >}}`. So in this case we'd have in our `.md` file something like

```md
{{< simplecast e31edbb0-e4ac-4d9f-aebc-3d613c2f972c >}}
```
and we'd have a shortcode template in Hugo that renders that like the iframe above.

**Comment by pdpinch** [comment]
I expect that we're stripping other ifames that we haven't discovered yet.

**Comment by aliceriot** [comment]
yes I think we probably are - although we'll need to take them on a case-by-case basis because for each one we want to support we'll have to do a separate hugo shortcode. So when I start with this one I'll try to make things a bit generalized so it can be easily extended for others later.

**Comment by pdpinch** [comment]
So the code was merged, but I don't see the podcast player on the link in the description. What needs to be done to actually fix this?

**Comment by aliceriot** [comment]
are you sure? I just visited <https://ocwnext.odl.mit.edu/courses/15-667-negotiation-and-conflict-management-spring-2001/sections/instructor-insights/> and this is what I see:

![podcast](https://user-images.githubusercontent.com/6207644/101539498-9ee52280-396c-11eb-8517-0b31b4e38c92.png)

is there an error in the console? The podcast player is an iframe, so maybe an extension or setting is blocking it?

**Comment by pdpinch** [comment]
Working for me now.
