### ISSUE TITLE
Search: Filter button is too large for column

### ISSUE THREAD

**Issue by pdpinch** [mitodl/hugo-course-publisher#337]
### Steps to Reproduce

https://ocwnext.odl.mit.edu/search/?d=Electrical%20Engineering%20and%20Computer%20Science&q=6.973

<img width="897" alt="image" src="https://user-images.githubusercontent.com/430126/98980194-472cd600-24ea-11eb-8940-54e4dd6da136.png">

**Comment by aliceriot** [comment]
how do you think we should handle this? we could do something like this:

![Screenshot from 2020-11-13 09-31-12](https://user-images.githubusercontent.com/6207644/99083127-181e6f00-2593-11eb-8eb0-bd19a266d1b8.png)

**Comment by aliceriot** [comment]
if you think that looks ok I can open a quick PR for that

**Comment by Ferdi** [comment]
maybe consider an alternative, more minimalist treatment given that data we have.  It seems like the pill treatment sort of amplifies the problem. @abdulkdawson

**Comment by aliceriot** [comment]
we have the same issue on Open as well:

![Screenshot from 2020-11-13 09-35-36](https://user-images.githubusercontent.com/6207644/99101853-31331a00-25ab-11eb-82be-b523bfa41405.png)

**Comment by abdulkdawson** [comment]
@Ferdi even if you remove the pill these title lengths are going to be an issue. The pills are a very small part of the problem and removing them does not cure anything.

**Comment by aliceriot** [comment]
for now do we want to go with a small change to allow the text to break onto two lines?

**Comment by abdulkdawson** [comment]
@abdulkdawson Yeah I think that makes sense.
