### ISSUE TITLE
Investigate image uploading and support for other content

### ISSUE THREAD

**Issue by noisecapella** [mitodl/hugo-course-publisher#34]
As a content author, I'd like to upload images in Netlify CMS

#### Acceptance Criteria:

Figure out how to answer these questions:

 - [ ] Should images be stored in git or on one of the supported media library services by Netlify CMS?
 - [ ] If we store the image in git, can we publish the updated content fast enough to allow Netlify CMS to view it?
 - [ ] If we store the image in S3, how are the images tracked and managed?
 - [ ] Do we need a CDN?
 - [ ] Do we need to support very large files like videos which should not be stored in git?
 - [ ] Do we need to support java or flash applets or other misc content? If so, how can we use the wysiwyg editor to do that upload and embed?
 - [ ] Does all of this work well with shortcodes?

**Comment by pdpinch** [comment]
no longer relevant
