### ISSUE TITLE
Resize Give button 

### ISSUE THREAD

**Issue by abdulkdawson** [mitodl/hugo-course-publisher#357]
The Give button on the OCW Homepage is too large. The required specs are outlined below:

Button: 158x50px
Text: 28px
Heart Icon: 30x26px

<img width="887" alt="Screen Shot 2020-11-18 at 11 48 06 AM" src="https://user-images.githubusercontent.com/49685474/99560499-ef7fe600-2993-11eb-89a7-7e6e06952d33.png">

**Comment by aliceriot** [comment]
cool, I'll address this in my PR for #314

**Comment by aliceriot** [comment]
I'm seeing also an orange button with white text here: https://projects.invisionapp.com/share/DFZBR47WPA7#/screens/436781958_OCW_NexGen_Homepage_11-04-2020_V2

do we want to go with the white-on-black version?

**Comment by abdulkdawson** [comment]
@aliceriot Sorry, I should have specified that. The Orange button is the one we are going with.
