### ISSUE TITLE
Home: Course card: Decrease padding

### ISSUE THREAD

**Issue by abdulkdawson** [mitodl/hugo-course-publisher#370]
Can we decrease the padding with the Course card. Areas that need to be address highlighted in the screenshot below. 

<img width="246" alt="Screen Shot 2020-11-19 at 10 28 51 AM" src="https://user-images.githubusercontent.com/49685474/99687012-2b798080-2a52-11eb-92da-5750859540bd.png">

**Comment by aliceriot** [comment]
@abdulkdawson how does this look? 

![Screenshot from 2020-12-01 09-33-21](https://user-images.githubusercontent.com/6207644/100753890-5f409880-33b8-11eb-856b-e9736914722a.png)

**Comment by abdulkdawson** [comment]
@aliceriot This looks good. Thank you!
