### ISSUE TITLE
Fix image border radius

### ISSUE THREAD

**Issue by noisecapella** [mitodl/hugo-course-publisher#380]
See the gap in the border at the upper left and right:

![Screenshot from 2020-11-19 16-47-36](https://user-images.githubusercontent.com/863262/99728169-04897180-2a87-11eb-9944-80e3b7a19985.png)

It looks like it's just a mismatch between the `img` border radius and the surrounding `.course-card`

**Comment by aliceriot** [comment]
haha, that's what testing with white-background images will get you :roll_eyes:
