### ISSUE TITLE
Hero Image too large

### ISSUE THREAD

**Issue by abdulkdawson** [mitodl/hugo-course-publisher#381]
The Hero image must be replaced with a smaller version of the file to increase loading speed.

<img width="1792" alt="Screen Shot 2020-11-19 at 4 55 15 PM" src="https://user-images.githubusercontent.com/49685474/99728810-01db4c00-2a88-11eb-9332-d585f1788c1f.png">

Attached is a jpg version of the hero image. 

![hero_image](https://user-images.githubusercontent.com/49685474/99729002-47981480-2a88-11eb-8aad-33e2d49d90c6.jpg)

**Comment by aliceriot** [comment]
@abdulkdawson this .jpg has the white line along the top that was on the .png before

**Comment by abdulkdawson** [comment]
@aliceriot I'm hot sure why this is happening but I'll take a look.

**Comment by abdulkdawson** [comment]
@aliceriot Try this version it should work. 

![hero_v3](https://user-images.githubusercontent.com/49685474/99998623-f9875780-2d8c-11eb-9272-eb1353074e57.jpg)

**Comment by abdulkdawson** [comment]
@aliceriot Let me know if you have any issues.

**Comment by aliceriot** [comment]
that looks perfect!
