### ISSUE TITLE
Reduce Spacing

### ISSUE THREAD

**Issue by abdulkdawson** [mitodl/hugo-course-publisher#385]
Reduce the spacing between the icon and the feature title. Currently, the padding is 24px. I would like to reduce this spacing down to 8px.

<img width="393" alt="Screen Shot 2020-11-19 at 5 23 59 PM" src="https://user-images.githubusercontent.com/49685474/99731826-731cfe00-2a8c-11eb-9c1d-ac5ede3086cc.png">

**Comment by aliceriot** [comment]
did a few tweaks, got it looking like this:

![Screenshot from 2020-11-23 12-06-13](https://user-images.githubusercontent.com/6207644/99992491-6813e780-2d84-11eb-99a7-d173019fefcd.png)

**Comment by abdulkdawson** [comment]
@aliceriot This looks good.

**Comment by aliceriot** [comment]
cool, I'll open a PR once the release is out the door
