### ISSUE TITLE
Apply hyperlink styling to topics in course home page

### ISSUE THREAD

**Issue by abdulkdawson** [mitodl/hugo-course-publisher#398]
The topcics should have the link styling similar to that of the instructor name, department, and level. Currently,  it is unclear that the Topics are links. 
<img width="502" alt="Screen Shot 2020-11-23 at 10 39 23 AM" src="https://user-images.githubusercontent.com/49685474/99982356-70662580-2d78-11eb-9899-d160fb38752f.png">

**Comment by aliceriot** [comment]
So basically we want to add text underlining?
