### ISSUE TITLE
Remove unnecessary isset checks

### ISSUE THREAD

**Issue by noisecapella** [mitodl/hugo-course-publisher#406]
For example https://github.com/mitodl/hugo-course-publisher/pull/400/files#r528835864

We should also look through our other checks and see if they are necessary or not

**Comment by pdpinch** [comment]
What impact will this have? Will it decrease the time needed for a build?

**Comment by noisecapella** [comment]
It probably won't change the build time. The concern is that there is content which could cause an error but is just rendering as empty HTML, and we should have an error there instead so we can identify and fix the issue. It's also likely that these checks are unnecessary so it would simplify the templates ab it.
