### ISSUE TITLE
video timestamp links are rendered as full video

### ISSUE THREAD

**Issue by alicewriteswrongs** [mitodl/hugo-course-publisher#423]
here's an example: https://ocw-beta.odl.mit.edu/courses/20-219-becoming-the-next-bill-nye-writing-and-hosting-the-educational-show-january-iap-2015/sections/day-3-storytellers-toolkit-pt.-1/

under the 'video chapters' heading the same video is rendered 7 times. this is the corresponding markdown:

```md
### Video chapters

*   {{< youtube AjK2zF9yN0k >}}
*   {{< youtube AjK2zF9yN0k >}}
*   {{< youtube AjK2zF9yN0k >}}
*   {{< youtube AjK2zF9yN0k >}}
*   {{< youtube AjK2zF9yN0k >}}
*   {{< youtube AjK2zF9yN0k >}}
*   {{< youtube AjK2zF9yN0k >}}
```

on the production version: https://ocw.mit.edu/courses/biological-engineering/20-219-becoming-the-next-bill-nye-writing-and-hosting-the-educational-show-january-iap-2015/day-3-storytellers-toolkit-pt.-1

it looks like these links are links to particular points in the video, they have a timestamp associated with them and clicking on them takes you to that point in the video.

**Comment by pdpinch** [comment]
replaced by https://github.com/mitodl/ocw-studio/issues/1043
