### ISSUE TITLE
MathJax support

### ISSUE THREAD

**Issue by gumaerc** [mitodl/hugo-course-publisher#58]
As a content author, I'd like to be able to write MathML and have it processed and displayed by MathJax.

#### Designs and Mockups

None yet, although I believe this should be accomplished with a custom Hugo shortcode.

#### Acceptance Criteria:

- [ ]  MathML can be written in some way and is displayed in the generated page

#### Out of Scope

- Nothing at the moment

**Comment by pdpinch** [comment]
@gumaerc do you think we can close this?

**Comment by gumaerc** [comment]
Yup!  Closing...
