### ISSUE TITLE
rawhtml shortcode is not defined

### ISSUE THREAD

**Issue by noisecapella** [mitodl/hugo-course-publisher#59]
### Steps to Reproduce

I used ocw-to-hugo on wgs-151-gender-health-and-society-spring-2016 (chosen at random), copied the output to `app/site/content` and ran `npm run build`.

### Expected Behavior

HTML output should be produced

### Actual Behavior

    node@8c3f3d2d2bc3:/usr/share/app$ npm run build:hugo
    
    > hugo-course-publisher@1.0.0 build:hugo /usr/share/app
    > hugo -d ../dist -s site -v
    
    INFO 2020/01/09 15:58:41 No translation bundle found for default language "en"
    INFO 2020/01/09 15:58:41 Translation func for language en not found, use default.
    INFO 2020/01/09 15:58:41 i18n not initialized; if you need string translations, check that you have a bundle in /i18n that matches the site language or the default language.
    INFO 2020/01/09 15:58:42 Using config file: 
    Building sites … INFO 2020/01/09 15:58:42 syncing static files to /usr/share/app/dist/
    WARN 2020/01/09 15:58:42 Page.URL is deprecated and will be removed in a future release. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url
    
                       | EN  
    +------------------+----+
      Pages            | 11  
      Paginator pages  |  0  
      Non-page files   |  0  
      Static files     | 27  
      Processed images |  0  
      Aliases          |  0  
      Sitemaps         |  1  
      Cleaned          |  0  
    
    Total in 28 ms
    node@8c3f3d2d2bc3:/usr/share/app$ npm run build:hugo
    
    > hugo-course-publisher@1.0.0 build:hugo /usr/share/app
    > hugo -d ../dist -s site -v
    
    INFO 2020/01/09 16:01:50 No translation bundle found for default language "en"
    INFO 2020/01/09 16:01:50 Translation func for language en not found, use default.
    INFO 2020/01/09 16:01:50 i18n not initialized; if you need string translations, check that you have a bundle in /i18n that matches the site language or the default language.
    INFO 2020/01/09 16:01:50 Using config file: 
    Building sites … INFO 2020/01/09 16:01:50 syncing static files to /usr/share/app/dist/
    Total in 23 ms
    Error: Error building site: "/usr/share/app/site/content/sections/lecture-slides.md:7:1": failed to extract shortcode: template for shortcode "rawhtml" not found
    npm ERR! code ELIFECYCLE
    npm ERR! errno 255
    npm ERR! hugo-course-publisher@1.0.0 build:hugo: `hugo -d ../dist -s site -v`
    npm ERR! Exit status 255
    npm ERR! 
    npm ERR! Failed at the hugo-course-publisher@1.0.0 build:hugo script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/node/.npm/_logs/2020-01-09T16_01_50_202Z-debug.log

**Comment by gumaerc** [comment]
This is my fault, as I should have created a PR for this shortcode before the initial PR for ocw-to-hugo was merged to master.  I don't think it's worth putting it in there now, as my tables PR in ocw-to-hugo removes the need for any shortcodes.  I will need to create a PR here on hugo-course-publisher, however, that allows raw HTML to be rendered in the Hugo output.  In the most recent versions of Hugo, they have changed from the "Blackfriday" markdown rendering engine to "Goldmark."  There is a configuration element you can put in your Hugo site config to enable raw HTML:

```
[markup.goldmark.renderer]
unsafe = true
```
